version: '3'
services:
  tgwgbot:
    environment:
      - VPN_PORT=${VPN_PORT}
    build:
      context: .
      dockerfile: Dockerfile
#    network_mode: host
    ports:
      - 51822:51822/udp
    privileged: true
    volumes:
     - testt:/app/
    cap_add:
      - NET_ADMIN
    restart: always
volumes:
 testt:
   driver: local
   driver_opts:
     type: 'none'
     o: 'bind'
     device: '~/proj/wg-tg-bot'
