version: '3'
services:
  tgwgbot:
    build:
      context: .
      dockerfile: Dockerfile
#    network_mode: host
    ports:
      - 51822:51822/udp
    privileged: true
    volumes:
      - test:/app/
#      - ~/wgtest/app /app/
    cap_add:
      - NET_ADMIN
    restart: always
volumes:
  test:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '~/proj/wg-tg-bot'