version: '3'
services:
  tgwgbot:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    ports:
      - 51822:51822/udp
    privileged: true
#    volumes:
#      - ~/wgtest/wireguard/ /etc/wireguard/
#      - ~/wgtest/app /app/
    cap_add:
      - NET_ADMIN
    restart: always
